### ISSUE TITLE
Fix Third Test

### ISSUE THREAD

**Issue by andrewhcook** [DPI-WE/longest-consecutive-sequence#2]
The third test is expecting ```ruby longest_consecutive([10, 5, 12, 3])``` to evaluate to 2 when it should be 1. 

The listed explanation is that 10,12 and 5,3 are viable consecutive arrays, but this is inconsistent with the rest of the lesson where consecutive is defined as incremented by one.

Either the array or the expected return value should be changed.

**Comment by heratyian** [comment]
Fixed 4db3dc8ceb930f3169994e43e34bd99687505a91 thanks @andrewhcook!
